# Generated by Django 5.2.3 on 2025-07-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='member',
            name='otp_exp',
        ),
        migrations.RemoveField(
            model_name='member',
            name='otp_verified',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('librarian', 'Librarian'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
