# Generated by Django 5.2.3 on 2025-07-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_member_otp_remove_member_otp_exp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='member',
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
